const lexicon = [
  {
    "oodham": "’ali",
    "english": "baby",
    "partOfSpeech": "noun",
    "pronunciation": "[ʔɑ.ɽi]",
    "reduplicated": "’a’al",
    "redup_pronunciation": "[ʔɑ.ʔɑɽ̥]",
    "redup_meaning": "children",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "hoa",
    "english": "basket",
    "partOfSpeech": "noun",
    "pronunciation": "[hwɑ]",
    "reduplicated": "hoaha",
    "redup_pronunciation": "[hwɑhɑ]",
    "redup_meaning": "baskets",
    "dialect": "Ak-Chin",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "vo’ikuḍ",
    "english": "bed",
    "partOfSpeech": "noun",
    "pronunciation": "[vɔ.ʔi.kuɖ̥]",
    "reduplicated": "vo:pikuḍ/wo:pikuḍ",
    "redup_pronunciation": "[vɔː.pi.kuɖ̥]",
    "redup_meaning": "bed",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "’iks",
    "english": "blanket, cloth",
    "partOfSpeech": "noun",
    "pronunciation": "[ʔiks]",
    "reduplicated": "’i’iks",
    "redup_pronunciation": "[ʔi.ʔiks]",
    "redup_meaning": "blankets, cloths",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "kahon",
    "english": "box",
    "partOfSpeech": "noun",
    "pronunciation": "[kɑ.hɔn̥]",
    "reduplicated": "kakhon",
    "redup_pronunciation": "[kɑk.kɔn]",
    "redup_meaning": "boxes",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "viappoi",
    "english": "boy, boys",
    "partOfSpeech": "noun",
    "pronunciation": "[vjɑp.pɔi]",
    "reduplicated": "vi:piop",
    "redup_pronunciation": "[viː.pjɔp]",
    "redup_meaning": "boys",
    "dialect": "",
    "examples": "Do: ’o wuḍ hegi viappoi?::Who is that boy?",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "’oag",
    "english": "brain",
    "partOfSpeech": "noun",
    "pronunciation": "[ʔɔɑg̥]",
    "reduplicated": "’oa’ag",
    "redup_pronunciation": "[ʔwɑg̥]",
    "redup_meaning": "brains",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "mi:tol",
    "english": "cat",
    "partOfSpeech": "noun",
    "pronunciation": "[miː.t̪ɔɽ̥]",
    "reduplicated": "mimitol",
    "redup_pronunciation": "[mi.mi.tɔɽ̥]",
    "redup_meaning": "cats",
    "dialect": "Ak-Chin",
    "examples": "Napt gegos g mi:tol?::Did you feed the cat?",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "mi:stol",
    "english": "cat",
    "partOfSpeech": "noun",
    "pronunciation": "[miː.t̪ɔɽ̥]",
    "reduplicated": "mimitol",
    "redup_pronunciation": "[mi.mi.tɔɽ̥]",
    "redup_meaning": "cats",
    "dialect": "Tohono O’odham",
    "examples": "Napt gegos g mi:tol?::Did you feed the cat?",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "daikuḍ",
    "english": "chair",
    "partOfSpeech": "noun",
    "pronunciation": "[d̪ɑi.kuɖ̥]",
    "reduplicated": "dadaikuḍ",
    "redup_pronunciation": "[d̪ɑ.d̪ɑi.kuɖ̥]",
    "redup_meaning": "chair",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "gogs",
    "english": "dog",
    "partOfSpeech": "noun",
    "pronunciation": "[gɔg̥s]",
    "reduplicated": "gogogs",
    "redup_pronunciation": "[gɔ.gɔg̥s]",
    "redup_meaning": "dogs",
    "dialect": "",
    "examples": "Hegi 'o ḍ ñ-gogsga.::That’s my dog.",
    "audio": "audio/audio1.mp3",
    "image": ""
  },
  {
    "oodham": "’ipuḍ",
    "english": "dress",
    "partOfSpeech": "noun",
    "pronunciation": "[ʔi.puɖ̥]",
    "reduplicated": "’i’ipuḍ",
    "redup_pronunciation": "[ʔi.ʔi.puɖ̥]",
    "redup_meaning": "dresses",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "wuhi",
    "english": "eye",
    "partOfSpeech": "noun",
    "pronunciation": "[wṳi]",
    "reduplicated": "vu:pui/wu:pui",
    "redup_pronunciation": "[vuː.pwi]",
    "redup_meaning": "eyes",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "cehia",
    "english": "girl",
    "partOfSpeech": "noun",
    "pronunciation": "[cɯ.hjɑ]",
    "reduplicated": "cecia",
    "redup_pronunciation": "[cɯ.cja]",
    "redup_meaning": "girls",
    "dialect": "",
    "examples": "Nap s-ma:c hegi cehia?::Do you know that girl?",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "mo’o",
    "english": "head",
    "partOfSpeech": "noun",
    "pronunciation": "[mɔ.ʔɔ]",
    "reduplicated": "mo:mĭ",
    "redup_pronunciation": "[mɔː.mĭ]",
    "redup_meaning": "heads",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "kanjul",
    "english": "lamp, electric light",
    "partOfSpeech": "noun",
    "pronunciation": "[kɑn.ɟuɽ̥]",
    "reduplicated": "kakanjul",
    "redup_pronunciation": "[kɑ.kɑn.ɟuɽ̥]",
    "redup_meaning": "lamps, lights",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "tonlig",
    "english": "light",
    "partOfSpeech": "noun",
    "pronunciation": "[tɔn.ɽig̥]",
    "reduplicated": "",
    "redup_pronunciation": "",
    "redup_meaning": "",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "kulañ",
    "english": "medicine",
    "partOfSpeech": "noun",
    "pronunciation": "[ku.ɽɑɲ̥]",
    "reduplicated": "kuklañ",
    "redup_pronunciation": "[kuk.ɽɑɲ̥]",
    "redup_meaning": "medicines",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "viohog",
    "english": "mesquite bean",
    "partOfSpeech": "noun",
    "pronunciation": "[vjɔ.hɔg̥]",
    "reduplicated": "",
    "redup_pronunciation": "",
    "redup_meaning": "",
    "dialect": "Ak-Chin",
    "examples": "Ant o vi:p g viohog.::I'm going to chew on some mesquite beans.",
    "audio": "",
    "image": "images/mesquitebean.png"
  },
  {
    "oodham": "kui",
    "english": "mesquite tree, tree (general)",
    "partOfSpeech": "noun",
    "pronunciation": "[kwi]",
    "reduplicated": "kukui",
    "redup_pronunciation": "[ku.kwi]",
    "redup_meaning": "mesquites, trees",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "ṣaliv",
    "english": "pair of pants",
    "partOfSpeech": "noun",
    "pronunciation": "[ʂɑ.ɽiv̥]",
    "reduplicated": "ṣaṣaliv",
    "redup_pronunciation": "[ʂɑ.ʂɑ.ɽiv̥]",
    "redup_meaning": "pairs of pants",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "tapial",
    "english": "paper",
    "partOfSpeech": "noun",
    "pronunciation": "[t̪ɑp.iɑɽ̥]",
    "reduplicated": "tatpial",
    "redup_pronunciation": "[t̪ɑtp.jɑɽ̥]",
    "redup_meaning": "papers",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "mo’ockuḍ",
    "english": "pillow",
    "partOfSpeech": "noun",
    "pronunciation": "[mɔ.ʔɔc.kuɖ̥]",
    "reduplicated": "mo:mckuḍ",
    "redup_pronunciation": "[mɔːmc.kuɖ̥]",
    "redup_meaning": "pillows",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "hodi",
    "english": "rock, stone",
    "partOfSpeech": "noun",
    "pronunciation": "[hɔ.d̪i]",
    "reduplicated": "hohodi",
    "redup_pronunciation": "[hɔ.hɔ.d̪i]",
    "redup_meaning": "rocks, stones",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "mumku",
    "english": "sick, being sick",
    "partOfSpeech": "verb, intransitive",
    "pronunciation": "[mum.ku]",
    "reduplicated": "",
    "redup_pronunciation": "",
    "redup_meaning": "",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "vindoñ",
    "english": "window",
    "partOfSpeech": "noun",
    "pronunciation": "[vin.d̪ɔɲ̥]",
    "reduplicated": "vipindoñ",
    "redup_pronunciation": "[vi.pin.d̪ɔɲ̥]",
    "redup_meaning": "windows",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "ki:",
    "english": "house",
    "partOfSpeech": "noun",
    "pronunciation": "[kiː]",
    "reduplicated": "ki:kĭ",
    "redup_pronunciation": "[kiː.kĭ]",
    "redup_meaning": "houses",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "hoas-ha’a",
    "english": "plate",
    "partOfSpeech": "noun",
    "pronunciation": "[hwɑ.sɑ.ʔɑ]",
    "reduplicated": "hoahas-haha’a",
    "redup_pronunciation": "[hwɑ.hɑ.sɑ.hɑ.ʔɑ]",
    "redup_meaning": "plates",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "’uskonakuḍ",
    "english": "fork",
    "partOfSpeech": "noun",
    "pronunciation": "[ʔus.kɔ.nɑ.kuɖ̥]",
    "reduplicated": "’u’uskonakuḍ",
    "redup_pronunciation": "[ʔu.ʔus.kɔ.nɑ.kuɖ̥]",
    "redup_meaning": "forks",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "kusal",
    "english": "spoon",
    "partOfSpeech": "noun",
    "pronunciation": "[ku.sɑɽ̥]",
    "reduplicated": "kuksal",
    "redup_pronunciation": "[kuk.sɑɽ̥]",
    "redup_meaning": "spoons",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "ku:paḍag",
    "english": "door",
    "partOfSpeech": "noun",
    "pronunciation": "[kuː.pɑ.ɖɑg̥]",
    "reduplicated": "ku:kpaḍag",
    "redup_pronunciation": "[kuːk.pɑ.ɖɑg̥]",
    "redup_meaning": "doors",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "kotoñ",
    "english": "shirt",
    "partOfSpeech": "noun",
    "pronunciation": "[kɔ.t̪ɔɲ]",
    "reduplicated": "koktoñ",
    "redup_pronunciation": "[kɔk.t̪ɔɲ]",
    "redup_meaning": "shirts",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "kamiṣ",
    "english": "shirt",
    "partOfSpeech": "noun",
    "pronunciation": "[kɑ.miʂ]",
    "reduplicated": "kakmiṣ",
    "redup_pronunciation": "[kɑk.miʂ]",
    "redup_meaning": "shirts",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "kalsi:do",
    "english": "sock",
    "partOfSpeech": "noun",
    "pronunciation": "[kɑɽ.siː.d̪ɔ]",
    "reduplicated": "kakalsi:do",
    "redup_pronunciation": "[kɑ.kɑɽ.siː.d̪ɔ]",
    "redup_meaning": "socks",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "ṣu:ṣk",
    "english": "shoe, pair of shoes",
    "partOfSpeech": "noun",
    "pronunciation": "[ʂuːʂk]",
    "reduplicated": "ṣuṣuṣk",
    "redup_pronunciation": "[ʂu.ʂuʂk]",
    "redup_meaning": "pairs of shoes",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "kolhi",
    "english": "fence",
    "partOfSpeech": "noun",
    "pronunciation": "[kɔɽ.hi]",
    "reduplicated": "kokolhi",
    "redup_pronunciation": "[kɔ.kɔɽ.hi]",
    "redup_meaning": "fences",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "kahio",
    "english": "leg",
    "partOfSpeech": "noun",
    "pronunciation": "[kɑ̤jɔ]",
    "reduplicated": "kakkio",
    "redup_pronunciation": "[kɑk.kjɔ]",
    "redup_meaning": "legs",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "taḍ",
    "english": "foot",
    "partOfSpeech": "noun",
    "pronunciation": "[t̪ɑɖ̥]",
    "reduplicated": "ta:taḍ",
    "redup_pronunciation": "[t̪ɑː.t̪ɑɖ̥]",
    "redup_meaning": "feet",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "mi:ṣ",
    "english": "table",
    "partOfSpeech": "noun",
    "pronunciation": "[miːʂ]",
    "reduplicated": "mi:mṣ",
    "redup_pronunciation": "[mimʂ]",
    "redup_meaning": "tables",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "mi:sa",
    "english": "table",
    "partOfSpeech": "noun",
    "pronunciation": "[miː.sɑ]",
    "reduplicated": "mimsa",
    "redup_pronunciation": "[mim.sɑ]",
    "redup_meaning": "tables",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "ha’a",
    "english": "pot",
    "partOfSpeech": "noun",
    "pronunciation": "[hɑ.ʔɑ]",
    "reduplicated": "haha’a",
    "redup_pronunciation": "[hɑ.hɑ.ʔɑ]",
    "redup_meaning": "pots",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "dagkoanakuḍ",
    "english": "towel",
    "partOfSpeech": "noun",
    "pronunciation": "[d̪ɑg̥.kɔɑ.nɑ.kuɖ̥]",
    "reduplicated": "dadagkoanakuḍ",
    "redup_pronunciation": "[d̪ɑ.d̪ɑg̥.kɔɑ.nɑ.kuɖ̥]",
    "redup_meaning": "towels",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "dagkoanakuḍ",
    "english": "napkin",
    "partOfSpeech": "noun",
    "pronunciation": "[d̪ɑg̥.kɔɑ.nɑ.kuɖ̥]",
    "reduplicated": "dadagkoanakuḍ",
    "redup_pronunciation": "[d̪ɑ.d̪ɑg̥.kɔɑ.nɑ.kuɖ̥]",
    "redup_meaning": "napkins",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "tovaṣ",
    "english": "handkerchief",
    "partOfSpeech": "noun",
    "pronunciation": "[tɔ.vɑʂ]",
    "reduplicated": "totvaṣ",
    "redup_pronunciation": "[tɔt.vɑʂ]",
    "redup_meaning": "handkerchiefs",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "monjel",
    "english": "headscarf",
    "partOfSpeech": "noun",
    "pronunciation": "[mɔn.ɟɯɽ̥]",
    "reduplicated": "momonjel",
    "redup_pronunciation": "[mɔ.mɔn.ɟɯɽ̥]",
    "redup_meaning": "headscarves",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "bayuka",
    "english": "necklace",
    "partOfSpeech": "noun",
    "pronunciation": "[bɑ.ju.kɑ]",
    "reduplicated": "babyuka",
    "redup_pronunciation": "[bɑb.ju.kɑ]",
    "redup_meaning": "necklaces",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "maskal",
    "english": "neckerchief",
    "partOfSpeech": "noun",
    "pronunciation": "[mɑs.kɑɽ̥]",
    "reduplicated": "mamskal",
    "redup_pronunciation": "[mɑms.kɑɽ̥]",
    "redup_meaning": "neckerchiefs",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "hu’u",
    "english": "star",
    "partOfSpeech": "noun",
    "pronunciation": "[hu.ʔu]",
    "reduplicated": "huhu’u",
    "redup_pronunciation": "[hu.hu.ʔu]",
    "redup_meaning": "stars",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "do’ag",
    "english": "mountain",
    "partOfSpeech": "noun",
    "pronunciation": "[d̪ɔ̰ɑg̥]",
    "reduplicated": "do:do’ag",
    "redup_pronunciation": "[d̪ɔː.dɑʔɑg̥]",
    "redup_meaning": "mountains",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "vo:g",
    "english": "road",
    "partOfSpeech": "noun",
    "pronunciation": "[vɔːg̥]",
    "reduplicated": "vopog",
    "redup_pronunciation": "[vɔ.pɔg̥]",
    "redup_meaning": "roads",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "vainomĭ",
    "english": "knife",
    "partOfSpeech": "noun",
    "pronunciation": "[vɑi.nɔ.mĭ̥]",
    "reduplicated": "vapainomĭ",
    "redup_pronunciation": "[vɑ.pɑi.nɔ.mĭ̥]",
    "redup_meaning": "knives",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "kavyu",
    "english": "horse",
    "partOfSpeech": "noun",
    "pronunciation": "[kɑv.ju]",
    "reduplicated": "kakavyu",
    "redup_pronunciation": "[kɑ.kɑv.ju]",
    "redup_meaning": "horses",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "ma:gina",
    "english": "car",
    "partOfSpeech": "noun",
    "pronunciation": "[mɑː.gi.nɑ]",
    "reduplicated": "mamagina",
    "redup_pronunciation": "[mɑ.mɑ.gi.nɑ]",
    "redup_meaning": "cars",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "kalit",
    "english": "car",
    "partOfSpeech": "noun",
    "pronunciation": "[kɑ.ɽit]",
    "reduplicated": "kaklit",
    "redup_pronunciation": "[kɑk.ɽit]",
    "redup_meaning": "cars",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "’o’ohon",
    "english": "book",
    "partOfSpeech": "noun",
    "pronunciation": "[ʔɔ.ʔɔ̆.hɔn]",
    "reduplicated": "’o’’ohon",
    "redup_pronunciation": "[ʔɔʔ.ʔɔ̆.hɔn]",
    "redup_meaning": "books",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "’i:bdag",
    "english": "heart",
    "partOfSpeech": "noun",
    "pronunciation": "[ʔiːb.d̪ɑg̥]",
    "reduplicated": "’i’ibdag",
    "redup_pronunciation": "[ʔi.ʔib.d̪ɑg̥]",
    "redup_meaning": "hearts",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "da:k",
    "english": "nose",
    "partOfSpeech": "noun",
    "pronunciation": "[d̪ɑːk]",
    "reduplicated": "da:dk",
    "redup_pronunciation": "[d̪ɑːd̪k]",
    "redup_meaning": "noses",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "na:k",
    "english": "ear",
    "partOfSpeech": "noun",
    "pronunciation": "[nɑːk]",
    "reduplicated": "na:nk",
    "redup_pronunciation": "[nɑːn̥k]",
    "redup_meaning": "ears",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "kusvo",
    "english": "neck",
    "partOfSpeech": "noun",
    "pronunciation": "[kus.vɔ]",
    "reduplicated": "kuksvo",
    "redup_pronunciation": "[kuks.vɔ]",
    "redup_meaning": "necks",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "ba:ṣo",
    "english": "chest",
    "partOfSpeech": "noun",
    "pronunciation": "[bɑː.ʂɔ]",
    "reduplicated": "babṣo",
    "redup_pronunciation": "[bɑb.ʂɔ]",
    "redup_meaning": "chests",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "kotva",
    "english": "shoulder",
    "partOfSpeech": "noun",
    "pronunciation": "[kɔt.vɑ]",
    "reduplicated": "koktva",
    "redup_pronunciation": "[kɔkt.vɑ]",
    "redup_meaning": "shoulders",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  },
  {
    "oodham": "to:n",
    "english": "knee",
    "partOfSpeech": "noun",
    "pronunciation": "[tɔːn̥]",
    "reduplicated": "to:ton",
    "redup_pronunciation": "[tɔː.tɔn̥]",
    "redup_meaning": "knees",
    "dialect": "",
    "examples": "",
    "audio": "",
    "image": ""
  }
];