const lexicon = [
  {
    "oodham": "cekva",
    "english": "ankle",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈcɯk.vɑ]",
    "reduplicated": "ceckva",
    "redup_pronunciation": "ankles",
    "redup_meaning": "[ˈcɯck.vɑ]",
    "dialect": "",
    "examples": "You’re going to hurt your ankle.",
    "audio": "audio/ankle.mp3",
    "image": ""
  },
  {
    "oodham": "’ali",
    "english": "baby",
    "pattern": "7",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈʔɑ.ɽi]",
    "reduplicated": "’a’al",
    "redup_pronunciation": "[ˈʔɑ.ʔɑɽ̥]",
    "redup_meaning": "children",
    "dialect": "",
    "examples": "No ṣoak g ’ali?::Is the baby crying? || Do: ’o ’am ha-ñu:kud g ’a’al?::Who’s taking care of the children?",
    "audio": "audio/baby.mp3",
    "image": ""
  },
  {
    "oodham": "’o:",
    "english": "back (of the body)",
    "pattern": "4",
    "partOfSpeech": "noun",
    "pronunciation": "[ʔɔː]",
    "reduplicated": "’o’o",
    "redup_pronunciation": "backs (of the body)",
    "redup_meaning": "[ˈʔɔ.ʔɔ]",
    "dialect": "",
    "examples": "S-mohogid g ñ-’o:.::My back itches.",
    "audio": "audio/backbody.mp3",
    "image": ""
  },
  {
    "oodham": "hoa",
    "english": "basket",
    "pattern": "7",
    "partOfSpeech": "noun",
    "pronunciation": "[hwɑ]",
    "reduplicated": "hoaha",
    "redup_pronunciation": "[ˈhwɑ.hɑ]",
    "redup_meaning": "baskets",
    "dialect": "Ak-Chin",
    "examples": "Ñ-vi:vi’ibaḍ ’at na:to ’i:da hoa.::My great-grandma made this basket. || ’Ant o ha’i ha-gagḍa g hoaha.::I’m going to sell some of the baskets.",
    "audio": "audio/basket.mp3",
    "image": ""
  },
  {
    "oodham": "vo’ikuḍ",
    "english": "bed",
    "pattern": "7",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈvɔ.ʔi.kuɖ̥]",
    "reduplicated": "vo:pikuḍ/wo:pikuḍ",
    "redup_pronunciation": "[ˈvɔː.pi.kuɖ̥]",
    "redup_meaning": "bed",
    "dialect": "",
    "examples": "Napt ’apec g ’e-vo’ikuḍ?::Did you make your bed?||Do: t o ha-ke:g c vo:pikuḍ?::Who’s going to clean the beds?",
    "audio": "audio/bed.mp3",
    "image": ""
  },
  {
    "oodham": "sa:vano",
    "english": "bedsheet",
    "pattern": "4",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈsɑː.vɑ.nɔ]",
    "reduplicated": "sasavano",
    "redup_pronunciation": "[ˈsɑ.sɑ.vɑ.nɔ]",
    "redup_meaning": "bedsheets",
    "dialect": "",
    "examples": "’I naggia g sa:vano.::Hang up the bedsheet.",
    "audio": "audio/bedsheet.mp3",
    "image": ""
  },
  {
    "oodham": "givuḍ",
    "english": "belt",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈgi.vuɖ̥]",
    "reduplicated": "gigivuḍ",
    "redup_pronunciation": "belts",
    "redup_meaning": "[ˈgi.vuɖ̥]",
    "dialect": "",
    "examples": "",
    "audio": "audio/belt.mp3",
    "image": ""
  },
  {
    "oodham": "’u’uhig",
    "english": "bird / birds",
    "pattern": "",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈʔu.ʔu.hig̥]",
    "reduplicated": "",
    "redup_pronunciation": "",
    "redup_meaning": "",
    "dialect": "",
    "examples": "Mu’i ’o ’an ñe:ñhim g ’u’uhig.::There are a lot of birds flying by.",
    "audio": "audio/bird.mp3",
    "image": ""
  },
  {
    "oodham": "’iks",
    "english": "blanket, cloth",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ʔiks]",
    "reduplicated": "’i’iks",
    "redup_pronunciation": "[ˈʔi.ʔiks]",
    "redup_meaning": "blankets, cloths",
    "dialect": "",
    "examples": "’I be:kai hegi ’iks mant o ñ-ce’ewi.::Bring me that blanket to cover with.||Ṣa:cu pt o na:to ’idam ’i’ikskaj?::What are you going to make with these pieces of cloth?",
    "audio": "audio/blanketcloth.mp3",
    "image": ""
  },
  {
    "oodham": "’e:’eḍ",
    "english": "blood",
    "pattern": "",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈʔɯː.ʔɯɖ̥]",
    "reduplicated": "",
    "redup_pronunciation": "",
    "redup_meaning": "",
    "dialect": "",
    "examples": "",
    "audio": "audio/blood.mp3",
    "image": ""
  },
  {
    "oodham": "gevo",
    "english": "bobcat",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈgɯ.vɔ]",
    "reduplicated": "gegevo",
    "redup_pronunciation": "bobcats",
    "redup_meaning": "[ˈgɯ.gɯ.vɔ]",
    "dialect": "",
    "examples": "S-’a’amḍak g gegevo.::The bobcats are friendly.",
    "audio": "audio/bobcat.mp3",
    "image": ""
  },
  {
    "oodham": "’o:’o",
    "english": "bone / bones",
    "pattern": "",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈʔɔː.ʔɔ]",
    "reduplicated": "",
    "redup_pronunciation": "",
    "redup_meaning": "",
    "dialect": "",
    "examples": "He’ekio ’o:’o ’an hab cu’ig t-cu:kug ’eḍa?::How many bones do we have in our body?",
    "audio": "audio/bone.mp3",
    "image": ""
  },
  {
    "oodham": "’o’ohon",
    "english": "book",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈʔɔ.ʔɔ̆.hɔn]",
    "reduplicated": "’o’’ohon",
    "redup_pronunciation": "[ˈʔɔʔ.ʔɔ̆.hɔn]",
    "redup_meaning": "books",
    "dialect": "",
    "examples": "Ñeokculid g ’o’ohon.::Read the book.",
    "audio": "audio/book.mp3",
    "image": ""
  },
  {
    "oodham": "vo:da",
    "english": "boot",
    "pattern": "3",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈvɔː.d̪ɑ]",
    "reduplicated": "vopda",
    "redup_pronunciation": "boots",
    "redup_meaning": "[ˈvɔː.d̪ɑ]",
    "dialect": "",
    "examples": "Ba: pt toa g ñ-vopda?::Where did you put my boots?",
    "audio": "audio/boot.mp3",
    "image": ""
  },
  {
    "oodham": "kahon",
    "english": "box",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈkɑ.hɔn̥]",
    "reduplicated": "kakhon",
    "redup_pronunciation": "[ˈkɑk.kɔn]",
    "redup_meaning": "boxes",
    "dialect": "",
    "examples": "’U:pam ce:k ’i:da kahon.::Put this box back.||’Oig ’am ha-ku:kpiok hegam kakhon.::Go ahead and open those boxes.",
    "audio": "audio/box.mp3",
    "image": ""
  },
  {
    "oodham": "viappoi",
    "english": "boy, boys",
    "pattern": "7",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈvjɑp.pɔi]",
    "reduplicated": "vi:piop",
    "redup_pronunciation": "[ˈviː.pjɔp]",
    "redup_meaning": "boys",
    "dialect": "",
    "examples": "Do: ’o wuḍ hegi viappoi?::Who is that boy?||Hegam vi:piop ’at ’an o cicvi g ṣoñgivul.::Those boys are going to play kickball.",
    "audio": "audio/boy.mp3",
    "image": ""
  },
  {
    "oodham": "’oag",
    "english": "brain",
    "pattern": "7",
    "partOfSpeech": "noun",
    "pronunciation": "[wɑ̰g̥]",
    "reduplicated": "’oa’ag",
    "redup_pronunciation": "[wɑʔɑg̥]",
    "redup_meaning": "brains",
    "dialect": "",
    "examples": "Ñeo’okĭ ’o wuḍ hegi mo ’an hab cu’ig t-’oag ’eḍ.::Language is what exists in our brains.",
    "audio": "audio/brain.mp3",
    "image": ""
  },
  {
    "oodham": "ṣa:mt",
    "english": "brick / bricks",
    "pattern": "",
    "partOfSpeech": "noun",
    "pronunciation": "[ʂɑːmt̪]",
    "reduplicated": "",
    "redup_pronunciation": "",
    "redup_meaning": "",
    "dialect": "",
    "examples": "Ha’i g na:to g bid ṣa:mt.::Make some adobe bricks.",
    "audio": "audio/brick.mp3",
    "image": ""
  },
  {
    "oodham": "’at",
    "english": "butt; bottom",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ʔɑt̪]",
    "reduplicated": "’a’at",
    "redup_pronunciation": "[ˈʔɑ.ʔɑt̪]",
    "redup_meaning": "butts; bottoms",
    "dialect": "",
    "examples": "Si ṣoñhi g ñ-’at!::S/he sure hit me on the butt!",
    "audio": "audio/butt.mp3",
    "image": ""
  },
  {
    "oodham": "votoñ",
    "english": "button",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈvɔ.t̪ɔɲ]",
    "reduplicated": "voptoñ",
    "redup_pronunciation": "buttons",
    "redup_meaning": "[ˈvɔ.t̪ɔɲ]",
    "dialect": "",
    "examples": "Mu’i voptoñ ’i:da ’ipuḍ.::This dress has many buttons.",
    "audio": "audio/button.mp3",
    "image": ""
  },
  {
    "oodham": "ma:gina",
    "english": "car",
    "pattern": "4",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈmɑː.gi.nɑ]",
    "reduplicated": "mamagina",
    "redup_pronunciation": "[ˈmɑ.mɑ.gi.nɑ]",
    "redup_meaning": "cars",
    "dialect": "",
    "examples": "No meḍ g ma:gina?::Is the car running?",
    "audio": "audio/carmagina.mp3",
    "image": ""
  },
  {
    "oodham": "kalit",
    "english": "car",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈkɑ.ɽit]",
    "reduplicated": "kaklit",
    "redup_pronunciation": "[ˈkɑk.ɽit]",
    "redup_meaning": "cars",
    "dialect": "",
    "examples": "’Ant o vakoa g ñ-kalit.::I’m going to wash my car.",
    "audio": "audio/carkalit.mp3",
    "image": ""
  },
  {
    "oodham": "mi:tol",
    "english": "cat",
    "pattern": "4",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈmiː.t̪ɔɽ̥]",
    "reduplicated": "mimitol",
    "redup_pronunciation": "[ˈmi.mi.tɔɽ̥]",
    "redup_meaning": "cats",
    "dialect": "Ak-Chin",
    "examples": "Napt gegos g mi:tol?::Did you feed the cat?",
    "audio": "audio/catmitol.mp3",
    "image": ""
  },
  {
    "oodham": "mi:stol",
    "english": "cat",
    "pattern": "3",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈmiː.t̪ɔɽ̥]",
    "reduplicated": "mimitol",
    "redup_pronunciation": "[ˈmims.tɔɽ̥]",
    "redup_meaning": "cats",
    "dialect": "Tohono O’odham",
    "examples": "Napt gegos g mi:tol?::Did you feed the cat?",
    "audio": "audio/catmistol.mp3",
    "image": ""
  },
  {
    "oodham": "daikuḍ",
    "english": "chair",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈd̪ɑi.kuɖ̥]",
    "reduplicated": "dadaikuḍ",
    "redup_pronunciation": "[ˈd̪ɑ.d̪ɑi.kuɖ̥]",
    "redup_meaning": "chair",
    "dialect": "",
    "examples": "’I be:kai hegi daikuḍ.::Bring that chair.",
    "audio": "audio/chair.mp3",
    "image": ""
  },
  {
    "oodham": "ka:m",
    "english": "cheek (of the face)",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[kɑːm]",
    "reduplicated": "ka:kam",
    "redup_pronunciation": "[ˈkɑː.kɑm]",
    "redup_meaning": "cheeks (of the face)",
    "dialect": "",
    "examples": "Dagkoan g ’e-ka:m.::Wipe your cheek.",
    "audio": "audio/cheekface.mp3",
    "image": ""
  },
  {
    "oodham": "ba:ṣo",
    "english": "chest",
    "pattern": "3",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈbɑː.ʂɔ]",
    "reduplicated": "babṣo",
    "redup_pronunciation": "[ˈbɑb.ʂɔ]",
    "redup_meaning": "chests",
    "dialect": "",
    "examples": "Si ñ-ṣoñhi ’an ñ-ba:ṣo ’an.::He sure punched my chest.",
    "audio": "audio/chest.mp3",
    "image": ""
  },
  {
    "oodham": "cevagĭ",
    "english": "cloud / clouds",
    "pattern": "",
    "partOfSpeech": "noun",
    "pronunciation": "[cɯː.vɑ.gĭ] ",
    "reduplicated": "",
    "redup_pronunciation": "",
    "redup_meaning": "",
    "dialect": "",
    "examples": "S-kokmagĭ g cevagĭ.::The clouds are gray.",
    "audio": "audio/cloud.mp3",
    "image": ""
  },
  {
    "oodham": "taṣ",
    "english": "day; sun; time",
    "pattern": "",
    "partOfSpeech": "noun",
    "pronunciation": "[t̪ɑʂ]",
    "reduplicated": "",
    "redup_pronunciation": "",
    "redup_meaning": "",
    "dialect": "",
    "examples": "",
    "audio": "audio/sun.mp3",
    "image": ""
  },
  {
    "oodham": "ma:kai",
    "english": "doctor",
    "pattern": "4",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈmɑː.kɑi]",
    "reduplicated": "mamakai",
    "redup_pronunciation": "doctors",
    "redup_meaning": "[ˈmɑ.mɑ.kɑi]",
    "dialect": "",
    "examples": "Napt 'am o ce:gim g ma:kai?::Are you going to go see the doctor?",
    "audio": "audio/doctor.mp3",
    "image": ""
  },
  {
    "oodham": "gogs",
    "english": "dog",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[gɔg̥s]",
    "reduplicated": "gogogs",
    "redup_pronunciation": "[ˈgɔ.gɔg̥s]",
    "redup_meaning": "dogs",
    "dialect": "",
    "examples": "Hegi 'o ḍ ñ-gogsga.::That’s my dog.",
    "audio": "audio/dog.mp3",
    "image": ""
  },
  {
    "oodham": "ku:paḍag",
    "english": "door",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈkuː.pɑ.ɖɑg̥]",
    "reduplicated": "ku:kpaḍag",
    "redup_pronunciation": "[ˈkuːk.pɑ.ɖɑg̥]",
    "redup_meaning": "doors",
    "dialect": "",
    "examples": "’I ku:p g ku:paḍag!::Close the door!",
    "audio": "audio/door.mp3",
    "image": ""
  },
  {
    "oodham": "’ipuḍ",
    "english": "dress",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈʔi.puɖ̥]",
    "reduplicated": "’i’ipuḍ",
    "redup_pronunciation": "[ˈʔi.ʔi.puɖ̥]",
    "redup_meaning": "dresses",
    "dialect": "",
    "examples": "Napt ’am daphiu g ñ-’ipuḍ?::Did you iron my dress?||’Att o va ha’i nolavt g vepcij ’i’ipuḍ.::We’re going to buy some new dresses.",
    "audio": "audio/dress.mp3",
    "image": ""
  },
  {
    "oodham": "na:k",
    "english": "ear",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[nɑːk]",
    "reduplicated": "na:nk",
    "redup_pronunciation": "[ˈnɑːn̥k]",
    "redup_meaning": "ears",
    "dialect": "",
    "examples": "S-ko’ok g ñ-na:k.::I have an earache.",
    "audio": "audio/ear.mp3",
    "image": ""
  },
  {
    "oodham": "wuhi",
    "english": "eye",
    "pattern": "7",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈwṳi]",
    "reduplicated": "vu:pui/wu:pui",
    "redup_pronunciation": "[ˈvuː.pwi]",
    "redup_meaning": "eyes",
    "dialect": "",
    "examples": "Pi g ’ab hu ṣa’i ta:tam g ’e-wuhi!::Don’t touch your eye!||S-momhogid g ñ-vu:pui.::My eyes itch.",
    "audio": "audio/eye.mp3",
    "image": ""
  },
  {
    "oodham": "kolhi",
    "english": "fence",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈkɔɽ.hi]",
    "reduplicated": "kokolhi",
    "redup_pronunciation": "[ˈkɔ.kɔɽ.hi]",
    "redup_meaning": "fences",
    "dialect": "",
    "examples": "Hi:m k ku:piok g kolhi.::Go open the fence.",
    "audio": "audio/fence.mp3",
    "image": ""
  },
  {
    "oodham": "’oidag",
    "english": "field",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈʔɔi.d̪ɑg̥]",
    "reduplicated": "’o’oidag",
    "redup_pronunciation": "[ˈʔɔ.ʔɔi.d̪ɑg̥]",
    "redup_meaning": "fields",
    "dialect": "",
    "examples": "Ṣa:cu m ’e’eṣa heg ’eḍa ’oidag?::What do you guys plant in that field?",
    "audio": "audio/field.mp3",
    "image": ""
  },
  {
    "oodham": "taḍ",
    "english": "foot",
    "pattern": "5",
    "partOfSpeech": "noun",
    "pronunciation": "[t̪ɑɖ̥]",
    "reduplicated": "ta:taḍ",
    "redup_pronunciation": "[ˈt̪ɑː.t̪ɑɖ̥]",
    "redup_meaning": "feet",
    "dialect": "",
    "examples": "S-kokok g ñ-ta:taḍ.::My feet hurt.",
    "audio": "audio/foot.mp3",
    "image": ""
  },
  {
    "oodham": "’uskonakuḍ",
    "english": "fork",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈʔus.kɔ.nɑ.kuɖ̥]",
    "reduplicated": "’u’uskonakuḍ",
    "redup_pronunciation": "[ˈʔu.ʔus.kɔ.nɑ.kuɖ̥]",
    "redup_meaning": "forks",
    "dialect": "",
    "examples": "Hema ñ-ma:k g ’uskonakuḍ.::Give me a fork.||Pi ’am hu vi’is g ’u’uskonakuḍ.::There are no forks left.",
    "audio": "audio/fork.mp3",
    "image": ""
  },
  {
    "oodham": "navoj",
    "english": "friend",
    "pattern": "7",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈnɑ.vɔɟ̥]",
    "reduplicated": "naupoj",
    "redup_pronunciation": "friends",
    "redup_meaning": "[ˈnɑu.pɔɟ̥]",
    "dialect": "",
    "examples": "No ḍ ’i:da g m-navoj?::Is this your friend?",
    "audio": "audio/friend.mp3",
    "image": ""
  },
  {
    "oodham": "ma:kig",
    "english": "gift; present / gifts; presents",
    "pattern": "",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈmɑː.kig̥]",
    "reduplicated": "",
    "redup_pronunciation": "",
    "redup_meaning": "",
    "dialect": "",
    "examples": "",
    "audio": "audio/gift.mp3",
    "image": ""
  },
  {
    "oodham": "cehia",
    "english": "girl",
    "pattern": "7",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈcɯ.hjɑ]",
    "reduplicated": "cecia",
    "redup_pronunciation": "[ˈcɯ.cja]",
    "redup_meaning": "girls",
    "dialect": "",
    "examples": "Nap s-ma:c hegi cehia?::Do you know that girl?",
    "audio": "audio/girl.mp3",
    "image": ""
  },
  {
    "oodham": "cevo",
    "english": "gopher",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈcɯ.vɔ]",
    "reduplicated": "cecevo",
    "redup_pronunciation": "gophers",
    "redup_meaning": "[ˈcɯ.cɯ.vɔ]",
    "dialect": "",
    "examples": "Hegi mo ’am si mu’i vapagt ’o hab ’e-’a’aga \"cevo\".::The thing that makes a bunch of holes in the groud is a \"gopher\".",
    "audio": "audio/gopher.mp3",
    "image": ""
  },
  {
    "oodham": "tovaṣ",
    "english": "handkerchief",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈtɔ.vɑʂ]",
    "reduplicated": "totvaṣ",
    "redup_pronunciation": "[ˈtɔt.vɑʂ]",
    "redup_meaning": "handkerchiefs",
    "dialect": "",
    "examples": "Dagkoan g ’ali wuhioṣa g ’e-tovaṣkaj.::Wipe the baby’s face with your handkerchief.",
    "audio": "audio/handkerchief.mp3",
    "image": ""
  },
  {
    "oodham": "mo’o",
    "english": "head",
    "pattern": "7",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈmɔ.ʔɔ]",
    "reduplicated": "mo:mĭ",
    "redup_pronunciation": "[ˈmɔː.mĭ]",
    "redup_meaning": "heads",
    "dialect": "",
    "examples": "Gaswuañ g ’ali mo’o.::Brush the baby’s hair.",
    "audio": "audio/head.mp3",
    "image": ""
  },
  {
    "oodham": "monjel",
    "english": "headscarf",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈmɔn.ɟɯɽ̥]",
    "reduplicated": "momonjel",
    "redup_pronunciation": "[ˈmɔ.mɔn.ɟɯɽ̥]",
    "redup_meaning": "headscarves",
    "dialect": "",
    "examples": "S-ke:gaj g monjelij.::Her headscarf is pretty.",
    "audio": "audio/headscarf.mp3",
    "image": ""
  },
  {
    "oodham": "’i:bdag",
    "english": "heart",
    "pattern": "4",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈʔiːb.d̪ɑg̥]",
    "reduplicated": "’i’ibdag",
    "redup_pronunciation": "[ˈʔi.ʔib.d̪ɑg̥]",
    "redup_meaning": "hearts",
    "dialect": "",
    "examples": "B ’o ma:s mo g ’i:bdag.::It looks like a heart.",
    "audio": "audio/heart.mp3",
    "image": ""
  },
  {
    "oodham": "kavyu",
    "english": "horse",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈkɑv.ju]",
    "reduplicated": "kakavyu",
    "redup_pronunciation": "[ˈkɑ.kɑv.ju]",
    "redup_meaning": "horses",
    "dialect": "",
    "examples": "No ’i:da ḍ m-kavyuga?::Is this your horse?",
    "audio": "audio/horse.mp3",
    "image": ""
  },
  {
    "oodham": "ki:",
    "english": "house",
    "pattern": "7",
    "partOfSpeech": "noun",
    "pronunciation": "[kiː]",
    "reduplicated": "ki:kĭ",
    "redup_pronunciation": "[ˈkiː.kĭ]",
    "redup_meaning": "houses",
    "dialect": "",
    "examples": "Hebi ke:k g ’e-ki:?::Where is your house?||Go:k ki:k ’o cu:c ’im hab ha’ap.::There are two houses on the other side of there.",
    "audio": "audio/house.mp3",
    "image": ""
  },
  {
    "oodham": "vagtalig",
    "english": "jacket; sweater",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈvɑg̥.tɑ.ɽig̥] ",
    "reduplicated": "vapagtalig",
    "redup_pronunciation": "[vɑ.pɑg̥.tɑ.ɽig̥]",
    "redup_meaning": "jackets; sweaters",
    "dialect": "",
    "examples": "’Ab g va:kid g ’e-vagtalig.::Put your jacket on.",
    "audio": "audio/jacket.mp3",
    "image": ""
  },
  {
    "oodham": "to:n",
    "english": "knee",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[tɔːn̥]",
    "reduplicated": "to:ton",
    "redup_pronunciation": "[ˈtɔː.tɔn̥]",
    "redup_meaning": "knees",
    "dialect": "",
    "examples": "Mant s-ko’okam ju: g ñ-to:n.::I hurt my knee.",
    "audio": "audio/knee.mp3",
    "image": ""
  },
  {
    "oodham": "vainomĭ",
    "english": "knife",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈvɑi.nɔ.mĭ̥]",
    "reduplicated": "vapainomĭ",
    "redup_pronunciation": "[ˈvɑ.pɑi.nɔ.mĭ̥]",
    "redup_meaning": "knives",
    "dialect": "",
    "examples": "Pi g ’am hu ṣa’i hekaj hegi vainomĭ.::Don’t use that knife.",
    "audio": "audio/knife.mp3",
    "image": ""
  },
  {
    "oodham": "kanjul",
    "english": "lamp, electric light",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈkɑn.ɟuɽ̥]",
    "reduplicated": "kakanjul",
    "redup_pronunciation": "[ˈkɑ.kɑn.ɟuɽ̥]",
    "redup_meaning": "lamps, lights",
    "dialect": "",
    "examples": "’Ant o nai g ñ-kanjul.::I’ll turn my light on.||Sa’i si s-mams g kakanul.::The lights are real bright.",
    "audio": "audio/lightlamp.mp3",
    "image": ""
  },
  {
    "oodham": "kahio",
    "english": "leg",
    "pattern": "7",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈkɑ̤.jɔ]",
    "reduplicated": "kakkio",
    "redup_pronunciation": "[ˈkɑk.kjɔ]",
    "redup_meaning": "legs",
    "dialect": "",
    "examples": "S-mohogid g ñ-kahi.::My leg itches.||No s-kokok g ’em-kakkio?::Do your legs hurt?",
    "audio": "audio/leg.mp3",
    "image": ""
  },
  {
    "oodham": "tonlig",
    "english": "light",
    "pattern": "",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈtɔn.ɽig̥]",
    "reduplicated": "",
    "redup_pronunciation": "",
    "redup_meaning": "",
    "dialect": "",
    "examples": "Nap ñeid hegi tonlig?::Do you see that light?",
    "audio": "audio/light.mp3",
    "image": ""
  },
  {
    "oodham": "hujuḍ",
    "english": "lizard",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈhu.ɟuɖ̥]",
    "reduplicated": "huhujuḍ",
    "redup_pronunciation": "lizards",
    "redup_meaning": "[ˈhu.ɟuɖ̥]",
    "dialect": "",
    "examples": "Hegi hujuḍ ’o ’an kolhi t-’ab him.::That lizard is crawling on the fence.",
    "audio": "audio/lizard.mp3",
    "image": ""
  },
  {
    "oodham": "kulañ",
    "english": "medicine",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈku.ɽɑɲ̥]",
    "reduplicated": "kuklañ",
    "redup_pronunciation": "[ˈkuk.ɽɑɲ̥]",
    "redup_meaning": "medicines",
    "dialect": "",
    "examples": "Ba’iñ g ’e-kulañ!::Take your medicine!||Hegi maṣ ḍ kulañ gagḍadam ’o si s-ma:c g na:nko ma:s kuklañ.::The pharmacists knows a lot about different types of medicine.",
    "audio": "audio/medicine.mp3",
    "image": ""
  },
  {
    "oodham": "viohog",
    "english": "mesquite bean",
    "pattern": "",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈvjɔ.hɔg̥]",
    "reduplicated": "",
    "redup_pronunciation": "",
    "redup_meaning": "",
    "dialect": "Ak-Chin",
    "examples": "Ant o vi:p g viohog.::I'm going to chew on some mesquite beans.",
    "audio": "audio/mesquitebean.mp3",
    "image": "images/mesquitebean.png"
  },
  {
    "oodham": "kui",
    "english": "mesquite tree, tree (general)",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[kwi]",
    "reduplicated": "kukui",
    "redup_pronunciation": "[ˈku.kwi]",
    "redup_meaning": "mesquites, trees",
    "dialect": "",
    "examples": "Cevaj g kui.::The tree is tall.",
    "audio": "audio/mesquitetree.mp3",
    "image": ""
  },
  {
    "oodham": "maṣad",
    "english": "moon; month",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈmɑ.ʂɑd̪̥]",
    "reduplicated": "mamṣad",
    "redup_pronunciation": "moons; months",
    "redup_meaning": "[ˈmɑm.ʂɑd̪̥]",
    "dialect": "",
    "examples": "",
    "audio": "audio/moon.mp3",
    "image": ""
  },
  {
    "oodham": "do’ag",
    "english": "mountain",
    "pattern": "7",
    "partOfSpeech": "noun",
    "pronunciation": "[d̪ɔ̰ɑg̥]",
    "reduplicated": "do:do’ag",
    "redup_pronunciation": "[ˈd̪ɔː.dɑ.ʔɑg̥]",
    "redup_meaning": "mountains",
    "dialect": "",
    "examples": "Heg o gḍ hu ki: do’ag da:m.::He lives on top of the mountain.",
    "audio": "audio/mountain.mp3",
    "image": ""
  },
  {
    "oodham": "mavid",
    "english": "mountain lion",
    "pattern": "7",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈmɑ.vid̪]",
    "reduplicated": "maipid",
    "redup_pronunciation": "mountain lions",
    "redup_meaning": "[ˈmɑi.pid̪]",
    "dialect": "",
    "examples": "Nap hebi hema ñeid g mavid?::Have you ever seen a mountain lion?",
    "audio": "audio/mountainlion.mp3",
    "image": ""
  },
  {
    "oodham": "nahagio",
    "english": "mouse; earring",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈnɑ̤ɑg.jɔ]",
    "reduplicated": "nanhagio",
    "redup_pronunciation": "[ˈnɑn.hɑ.gjɔ]",
    "redup_meaning": "mice; earrings",
    "dialect": "",
    "examples": "Mu’i ’o ha’icu g nanhagio heg ’eḍa ’oidag.::There are lot of mice in that field.",
    "audio": "audio/mouse.mp3",
    "image": ""
  },
  {
    "oodham": "ce:gig",
    "english": "name",
    "pattern": "3",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈcɯː.gig̥]",
    "reduplicated": "cecgig",
    "redup_pronunciation": "names",
    "redup_meaning": "[ˈcɯc.gig̥]",
    "dialect": "",
    "examples": "Write your name down.",
    "audio": "audio/name.mp3",
    "image": ""
  },
  {
    "oodham": "kusvo",
    "english": "neck",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈkus.vɔ]",
    "reduplicated": "kuksvo",
    "redup_pronunciation": "[ˈkuks.vɔ]",
    "redup_meaning": "necks",
    "dialect": "",
    "examples": "Hukṣ ’at g ñ-kusvo.::S/he scratched my neck.",
    "audio": "audio/neck.mp3",
    "image": ""
  },
  {
    "oodham": "maskal",
    "english": "neckerchief",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈmɑs.kɑɽ̥]",
    "reduplicated": "mamskal",
    "redup_pronunciation": "[ˈmɑms.kɑɽ̥]",
    "redup_meaning": "neckerchiefs",
    "dialect": "",
    "examples": "S-vegĭ maskal g vakial.::The cowboy has a red neckerchief.",
    "audio": "audio/neckerchief.mp3",
    "image": ""
  },
  {
    "oodham": "bayuka",
    "english": "necklace",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈbɑ.ju.kɑ]",
    "reduplicated": "babyuka",
    "redup_pronunciation": "[ˈbɑb.ju.kɑ]",
    "redup_meaning": "necklaces",
    "dialect": "",
    "examples": "Ñ-bayuka ’o ḍ ’o:la.::My necklace is gold.",
    "audio": "audio/necklace.mp3",
    "image": ""
  },
  {
    "oodham": "ho’ibaḍ",
    "english": "needle",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈhɔ.ʔi.bɑɖ̥]",
    "reduplicated": "hoho’ibaḍ",
    "redup_pronunciation": "needles",
    "redup_meaning": "[ˈhɔ..hɔ.ʔi.bɑɖ̥]",
    "dialect": "",
    "examples": "S-mu’uk g ho’ibaḍ.::The needle is sharp.",
    "audio": "audio/needle.mp3",
    "image": ""
  },
  {
    "oodham": "da:k",
    "english": "nose",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[d̪ɑːk]",
    "reduplicated": "da:dk",
    "redup_pronunciation": "[ˈd̪ɑːd̪k]",
    "redup_meaning": "noses",
    "dialect": "",
    "examples": "S-mohogid g ñ-da:k.::My nose itches.",
    "audio": "audio/nose.mp3",
    "image": ""
  },
  {
    "oodham": "ṣaliv",
    "english": "pair of pants",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈʂɑ.ɽiv̥]",
    "reduplicated": "ṣaṣaliv",
    "redup_pronunciation": "[ˈʂɑ.ʂɑ.ɽiv̥]",
    "redup_meaning": "pairs of pants",
    "dialect": "",
    "examples": "’Ant o vakoa g ñ-ṣaliv.::I’m going to wash my pants.||’An g ha-na:ngia g ṣaṣaliv.::Hang up the pairs of pants.",
    "audio": "audio/pants.mp3",
    "image": ""
  },
  {
    "oodham": "tapial",
    "english": "paper",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈt̪ɑp.iɑɽ̥]",
    "reduplicated": "tatpial",
    "redup_pronunciation": "[ˈt̪ɑtp.jɑɽ̥]",
    "redup_meaning": "papers",
    "dialect": "",
    "examples": "’O’ohon g ’e-ce:gig ’id ’ab tapial.::Sign your name on this paper.",
    "audio": "audio/paper.mp3",
    "image": ""
  },
  {
    "oodham": "la:bis",
    "english": "pencil",
    "pattern": "4",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈɽɑː.bis] ",
    "reduplicated": "lalabis",
    "redup_pronunciation": "[ˈɽɑ.ɽɑ.bis]",
    "redup_meaning": "pencils",
    "dialect": "",
    "examples": "Nap ge la:bis?::Do you have a pencil?",
    "audio": "audio/pencil.mp3",
    "image": ""
  },
  {
    "oodham": "mo’ockuḍ",
    "english": "pillow",
    "pattern": "7",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈmɔ.ʔɔc.kuɖ̥]",
    "reduplicated": "mo:mckuḍ",
    "redup_pronunciation": "[ˈmɔːmc.kuɖ̥]",
    "redup_meaning": "pillows",
    "dialect": "",
    "examples": "Ge habaḍk g ñ-mo’ockuḍ!::My pillow’s just flat!",
    "audio": "audio/pillow.mp3",
    "image": ""
  },
  {
    "oodham": "hoas-ha’a",
    "english": "plate",
    "pattern": "7",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈhwɑ.sɑ.ʔɑ]",
    "reduplicated": "hoahas-haha’a",
    "redup_pronunciation": "[ˈhwɑ.hɑ.ˌsɑ.hɑ.ʔɑ]",
    "redup_meaning": "plates",
    "dialect": "",
    "examples": "Hema g hekaj g hoas-ha’a.::Use a plate.||M o si ha-vapkoa g hoahas-haha’a.::Wash the plates good.",
    "audio": "audio/plate.mp3",
    "image": ""
  },
  {
    "oodham": "kalna:yo",
    "english": "pomegranate / pomegranates",
    "pattern": "",
    "partOfSpeech": "noun",
    "pronunciation": "[kɑɽ.ˈnɑː.jɔ]",
    "reduplicated": "",
    "redup_pronunciation": "",
    "redup_meaning": "",
    "dialect": "",
    "examples": "Si s-io’ovĭ ’i:da kalna:yo.::This pomegranate is really sweet.",
    "audio": "audio/pomegranate.mp3",
    "image": ""
  },
  {
    "oodham": "ha’a",
    "english": "pot",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈhɑ.ʔɑ]",
    "reduplicated": "haha’a",
    "redup_pronunciation": "[ˈhɑ.hɑ.ʔɑ]",
    "redup_meaning": "pots",
    "dialect": "",
    "examples": "’Ant o hekaj ’i:da ha’a mant o na:to g mu:ñ.::I’m going to use this pot to make beans.",
    "audio": "audio/pot.mp3",
    "image": ""
  },
  {
    "oodham": "ṣavkuḍ",
    "english": "rattle",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈʂɑv̥.kuɖ̥]",
    "reduplicated": "ṣaṣavkuḍ",
    "redup_pronunciation": "rattles",
    "redup_meaning": "[ˈʂɑ.ʂɑv̥.kuɖ̥]",
    "dialect": "",
    "examples": "Do: t m-na:tojul ’i:da ṣavkuḍ?",
    "audio": "audio/rattle.mp3",
    "image": ""
  },
  {
    "oodham": "’añilo",
    "english": "ring",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈʔɑː.ɲi.ɽɔ]",
    "reduplicated": "’a’añilo",
    "redup_pronunciation": "[ˈʔɑ.ʔɑ.ɲi.ɽɔ]",
    "redup_meaning": "rings",
    "dialect": "",
    "examples": "Hekĭ ’ant hu wua g ñ-’añilo.::I lost my ring.",
    "audio": "audio/ring.mp3",
    "image": ""
  },
  {
    "oodham": "vo:g",
    "english": "road",
    "pattern": "4",
    "partOfSpeech": "noun",
    "pronunciation": "[vɔːg̥]",
    "reduplicated": "vopog",
    "redup_pronunciation": "[ˈvɔ.pɔg̥]",
    "redup_meaning": "roads",
    "dialect": "",
    "examples": "Ba: ’o ka:c g vo:g?::Where is the road?",
    "audio": "audio/road.mp3",
    "image": ""
  },
  {
    "oodham": "taḍai",
    "english": "roadrunner",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[t̪ɑ.ɖɑi]",
    "reduplicated": "tataḍai",
    "redup_pronunciation": "[t̪ɑ.t̪ɑ.ɖɑi]",
    "redup_meaning": "roadruners",
    "dialect": "",
    "examples": "Gm hu me: g taḍai.::The roadrunner ran over there.",
    "audio": "audio/roadrunner.mp3",
    "image": ""
  },
  {
    "oodham": "hodi",
    "english": "rock, stone",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈhɔ.d̪i]",
    "reduplicated": "hohodi",
    "redup_pronunciation": "[ˈhɔ.hɔ.d̪i]",
    "redup_meaning": "rocks, stones",
    "dialect": "",
    "examples": "Hema g da’icud g hodi!::Throw a rock!",
    "audio": "audio/rock.mp3",
    "image": ""
  },
  {
    "oodham": "tatk",
    "english": "root / roots",
    "pattern": "",
    "partOfSpeech": "noun",
    "pronunciation": "[t̪ɑt̪k]",
    "reduplicated": "",
    "redup_pronunciation": "",
    "redup_meaning": "",
    "dialect": "",
    "examples": "Ha’i ’o ’am hi va hekaj g hovij tatk mat o ha-na:to g hoaha.::Some people use banana yucca root to make baskets.",
    "audio": "audio/root.mp3",
    "image": ""
  },
  {
    "oodham": "maṣcamakuḍ",
    "english": "school",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈmɑʂ.cɑ.mɑ.kuɖ̥]",
    "reduplicated": "mamṣcamakuḍ",
    "redup_pronunciation": "schools",
    "redup_meaning": "[ˈmɑmʂ.cɑ.mɑ.kuɖ̥]",
    "dialect": "",
    "examples": "Ba: ’o ke:k g maṣcamakuḍ?::Where is the school located?",
    "audio": "audio/school.mp3",
    "image": ""
  },
  {
    "oodham": "kotoñ",
    "english": "shirt",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈkɔ.t̪ɔɲ]",
    "reduplicated": "koktoñ",
    "redup_pronunciation": "[ˈkɔk.t̪ɔɲ]",
    "redup_meaning": "shirts",
    "dialect": "",
    "examples": "’Ab g va:kid ’i:da kotoñ.::Put this shirt on.",
    "audio": "audio/shirtkoton.mp3",
    "image": ""
  },
  {
    "oodham": "kamiṣ",
    "english": "shirt",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈkɑ.miʂ]",
    "reduplicated": "kakmiṣ",
    "redup_pronunciation": "[ˈkɑk.miʂ]",
    "redup_meaning": "shirts",
    "dialect": "",
    "examples": "’I naggia hegi kotoñ::Hang that shirt up.",
    "audio": "audio/shirtkamis.mp3",
    "image": ""
  },
  {
    "oodham": "ṣu:ṣk",
    "english": "shoe, pair of shoes",
    "pattern": "4",
    "partOfSpeech": "noun",
    "pronunciation": "[ʂuːʂk]",
    "reduplicated": "ṣuṣuṣk",
    "redup_pronunciation": "[ˈʂu.ʂuʂk]",
    "redup_meaning": "pairs of shoes",
    "dialect": "",
    "examples": "Ñeid g ñ-ṣu:ṣk!::Look at my shoes!",
    "audio": "audio/shoe.mp3",
    "image": ""
  },
  {
    "oodham": "kotva",
    "english": "shoulder",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈkɔt.vɑ]",
    "reduplicated": "koktva",
    "redup_pronunciation": "[ˈkɔkt.vɑ]",
    "redup_meaning": "shoulders",
    "dialect": "",
    "examples": "No s-kokok g m-koktva?::Do you shoulders hurt?",
    "audio": "audio/shoulder.mp3",
    "image": ""
  },
  {
    "oodham": "mumku",
    "english": "sick, being sick",
    "pattern": "",
    "partOfSpeech": "verb, intransitive",
    "pronunciation": "[ˈmum.ku]",
    "reduplicated": "",
    "redup_pronunciation": "",
    "redup_meaning": "",
    "dialect": "",
    "examples": "Nap mumku?::Are you sick?",
    "audio": "audio/sick.mp3",
    "image": ""
  },
  {
    "oodham": "koṣva",
    "english": "skull",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈkɔʂ.vɑ]",
    "reduplicated": "kokṣva",
    "redup_pronunciation": "skulls",
    "redup_meaning": "[ˈkɔkʂ.vɑ]",
    "dialect": "",
    "examples": "’I:da s-kavk ha’icu mo ’an hab cu’ig t-mo’o ’eḍ ’o ḍ \"koṣva\".::This hard thing in our heads is the skull.",
    "audio": "audio/skull.mp3",
    "image": ""
  },
  {
    "oodham": "kalsi:do",
    "english": "sock",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈkɑɽ.siː.d̪ɔ]",
    "reduplicated": "kakalsi:do",
    "redup_pronunciation": "[ˈkɑ.kɑɽ.siː.d̪ɔ]",
    "redup_meaning": "socks",
    "dialect": "",
    "examples": "Gḍ g hu toa’i g ’e-kakalsi:do.::Put your socks away.",
    "audio": "audio/sock.mp3",
    "image": ""
  },
  {
    "oodham": "ṣondal",
    "english": "soldier",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈʂɔn.d̪ɑɽ̥]",
    "reduplicated": "ṣoṣondal",
    "redup_pronunciation": "soldiers",
    "redup_meaning": "[ˈʂɔ.ʂɔn.d̪ɑɽ̥]",
    "dialect": "",
    "examples": "Is your child a soldier (in the army)?",
    "audio": "audio/soldier.mp3",
    "image": ""
  },
  {
    "oodham": "kusal",
    "english": "spoon",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈku.sɑɽ̥]",
    "reduplicated": "kuksal",
    "redup_pronunciation": "[ˈkuk.sɑɽ̥]",
    "redup_meaning": "spoons",
    "dialect": "",
    "examples": "Hugiñ g ’e-kusalkaj.::Eat it with your spoon.||Ha’i ’i ’u’ukai g kuksal.::Bring some spoons.",
    "audio": "audio/spoon.mp3",
    "image": ""
  },
  {
    "oodham": "hu’u",
    "english": "star",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈhu.ʔu]",
    "reduplicated": "huhu’u",
    "redup_pronunciation": "[ˈhu.hu.ʔu]",
    "redup_meaning": "stars",
    "dialect": "",
    "examples": "Si tonoḍ g huhu’u.::The stars are really shining.",
    "audio": "audio/star.mp3",
    "image": ""
  },
  {
    "oodham": "’u:s",
    "english": "stick",
    "pattern": "4",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈʔuːs]",
    "reduplicated": "’u’us",
    "redup_pronunciation": "sticks",
    "redup_meaning": "[ˈʔuːs]",
    "dialect": "",
    "examples": "Ha’i ’i ’u’ukai g ’u’us.::Bring some sticks over here.",
    "audio": "audio/stick.mp3",
    "image": ""
  },
  {
    "oodham": "vo:k",
    "english": "stomach; belly",
    "pattern": "1",
    "partOfSpeech": "noun",
    "pronunciation": "[vɔːk]",
    "reduplicated": "vo:pk",
    "redup_pronunciation": "[vɔːpk]",
    "redup_meaning": "stomachs; bellies",
    "dialect": "",
    "examples": "S-ko’ok g ñ-vo:k.::My stomach hurts.",
    "audio": "audio/somtach.mp3",
    "image": ""
  },
  {
    "oodham": "mi:ṣ",
    "english": "table",
    "pattern": "3",
    "partOfSpeech": "noun",
    "pronunciation": "[miːʂ]",
    "reduplicated": "mimṣ",
    "redup_pronunciation": "[ˈmimʂ]",
    "redup_meaning": "tables",
    "dialect": "",
    "examples": "’An g da:ṣ g ko:ba mi:ṣ da:m.::Set the cup on the table.||M o si ha-dadagkoa g mimṣ.::Wipe the tables down.",
    "audio": "audio/table.mp3",
    "image": ""
  },
  {
    "oodham": "mi:sa",
    "english": "table",
    "pattern": "3",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈmiː.sɑ]",
    "reduplicated": "mimsa",
    "redup_pronunciation": "[ˈmim.sɑ]",
    "redup_meaning": "tables",
    "dialect": "",
    "examples": "Napt dagĭto g ’e-lialga ’an mi:sa da:m?::Did you leave your money on the table?",
    "audio": "audio/tablemisa.mp3",
    "image": ""
  },
  {
    "oodham": "ñe:ñ",
    "english": "tongue",
    "pattern": "4",
    "partOfSpeech": "noun",
    "pronunciation": "[ɲɯːɲ]",
    "reduplicated": "ñeñeñ",
    "redup_pronunciation": "[ˈɲɯ.ɲɯɲ]",
    "redup_meaning": "tongues",
    "dialect": "",
    "examples": "Napt mehi g ’e-ne:ñ?::Did you burn your tongue?",
    "audio": "audio/tongue.mp3",
    "image": ""
  },
  {
    "oodham": "ta:tamĭ",
    "english": "tooth / teeth",
    "pattern": "",
    "partOfSpeech": "noun",
    "pronunciation": "[t̪ɑː.t̪ɑ.mĭ]",
    "reduplicated": "",
    "redup_pronunciation": "",
    "redup_meaning": "",
    "dialect": "",
    "examples": "Kegcun g ’e-ta:tamĭ!::Brush your teeth!",
    "audio": "audio/tooth.mp3",
    "image": ""
  },
  {
    "oodham": "cemait",
    "english": "tortilla",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈcɯ.mɑit̥]",
    "reduplicated": "cecemait",
    "redup_pronunciation": "tortillas",
    "redup_meaning": "[ˈcɯ.cɯ.mɑit̥]",
    "dialect": "",
    "examples": "Hema ñ-ma:k g cemait.::Pass me a tortilla.",
    "audio": "audio/tortilla.mp3",
    "image": ""
  },
  {
    "oodham": "dagkoanakuḍ",
    "english": "towel; napkin",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈd̪ɑg̥.kɔɑ.nɑ.kuɖ̥]",
    "reduplicated": "dadagkoanakuḍ",
    "redup_pronunciation": "[ˈd̪ɑ.d̪ɑg̥.kɔɑ.nɑ.kuɖ̥]",
    "redup_meaning": "towels; napkins",
    "dialect": "",
    "examples": "Kiap s-vapḍag g dadagkoanakuḍ.::The towels are still wet.",
    "audio": "audio/towel.mp3",
    "image": ""
  },
  {
    "oodham": "tlo:gi",
    "english": "truck",
    "pattern": "7",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈtɽɔː.gi]",
    "reduplicated": "tlolgi",
    "redup_pronunciation": "trucks",
    "redup_meaning": "[ˈtɽɔɽ.gi]",
    "dialect": "",
    "examples": "Napt nolavt hegi tlo:gi?::Did you buy that truck?",
    "audio": "audio/truck.mp3",
    "image": ""
  },
  {
    "oodham": "vindoñ",
    "english": "window",
    "pattern": "2",
    "partOfSpeech": "noun",
    "pronunciation": "[ˈvin.d̪ɔɲ̥]",
    "reduplicated": "vipindoñ",
    "redup_pronunciation": "[ˈvi.pin.d̪ɔɲ̥]",
    "redup_meaning": "windows",
    "dialect": "",
    "examples": "’I ku:p g vindoñ.::Close the window.||Ṣa s-bibtagĭ g vipindoñ.::The windows are kind of dirty.",
    "audio": "audio/window.mp3",
    "image": ""
  }
];